# Generated by Django 5.2.17 on 2026-10-02 15:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aeropuertos',
                'ordering': ['ciudad', 'codigo_iata'],
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad_economy', models.IntegerField()),
                ('capacidad_primera', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'aviones',
                'db_table': 'aviones',
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('fecha_operacion', models.DateField()),
                ('hora_partida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('precio_economy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_primera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asientos_disponibles_economy', models.IntegerField()),
                ('asientos_disponibles_primera', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_llegada', to='vuelos.aeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_salida', to='vuelos.aeropuerto')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.avion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vuelos',
                'ordering': ['fecha_operacion', 'hora_partida'],
                'constraints': [models.UniqueConstraint(fields=('numero_vuelo', 'fecha_operacion'), name='vuelo_numero_fecha_unico'), models.CheckConstraint(condition=models.Q(('aeropuerto_origen', models.F('aeropuerto_destino')), _negated=True), name='vuelo_origen_distinto_destino'), models.CheckConstraint(condition=models.Q(('asientos_disponibles_economy__gte', 0)), name='vuelo_asientos_economy_no_negativos'), models.CheckConstraint(condition=models.Q(('asientos_disponibles_primera__gte', 0)), name='vuelo_asientos_primera_no_negativos')],
            },
        ),
    ]
